title: Miguel Angel Ahumada Centeno # your name (or website title) here
logo: "/Perfil.jpg?raw=True" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S. in Physics 
  <br><br>
  Degree in physics with a proficient knowledge in statistics, mathematics, physics and analytics. As a scientist, I understand the important value of measurement as the first step in the control and improvement of any process. Seeking to apply understanding of business operations and analytics tools as a Data Analyst. 
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/ahumadacenteno/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
